### ISSUE TITLE
Musculoskeletal motions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obo-behavior/behavior-ontology#10]
```
Can you add class such as 'supination'. See:

http://en.wikipedia.org/wiki/Category:Anatomical_terms_of_motion

From there I can request specific terms such as "forearm supination", "jaw 
adduction" etc
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 14 Aug 2012 at 11:56

**Comment by reality** [comment]
also pronation

**Comment by DitchingIt** [comment]
@cmungall @aclark-binghamton-edu @pmidford @dosumis Was there ever a discussion about whether to add planar/articular movements into NBO? Currently we have head movements like rotation, eyelid movements like blinking, and jaw movements like biting. I can see such descriptions used in definitions of types of movement, but I wonder if it meets our objectives to make them behavior classes in themselves? On the other hand, aside from SNOMED, where else could they be located?

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt Well, Peter and I did not have anything to do with the contents of the NBO...at least I did not. But I am a little confused by the question...ABO has the "operational terms" arm in order to allow descriptions when functional aspects are unknown (or when even what constitutes "a behavior" is not specifiable).  These events occur within so many other behaviors or functional sequences (e.g. display or attack or eating) that I don't see them standing alone.  But maybe I am not interpreting your suggestion correctly.  NBO includes "voluntary" vs "involuntary" movements, by the way, which is a distinction that I cannot see making in most cases.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu Thanks. I didn't intend to make a suggestion, just to explore how reductionist NBO wants to be. I like the ABO separation between operational and functional terms. But do we want to go down the road of subdividing 'chew' for example, into the classes of jaw adduction, depression, protrusion, retrusion, and excursion?

Now that I am tempted to make a suggestion, I suggest that we NOT go down to the level of [anatomical terms of motion](https://en.wikipedia.org/wiki/Anatomical_terms_of_motion) except where a single motion might also have a complete symbolic meaning, e.g. protrusion of the jaw can be a method of pointing. NB: This still allows use of terms of motion in a definition, e.g. begging might involve dorsiflexion of the hands.

**Comment by aclark-binghamton-edu** [comment]
Totally agree. There are anatomical ontologies and probably related ones I don’t know about. ABO made an overt decision to use others out there and not invent any more wheels. Ie describe the behavior but don’t list out component parts. I second your exploratory suggestion! Sent from my iPhoneOn Apr 6, 2023, at 5:29 PM, Ditch Townsend ***@***.***> wrote:﻿
@aclark-binghamton-edu Thanks. I didn't intend to make a suggestion, just to explore how reductionist NBO wants to be. I like the ABO separation between operational and functional terms. But do we want to go down the road of subdividing 'chew' for example, into the classes of jaw adduction, depression, protrusion, retrusion, and excursion?
Now that I am tempted to make a suggestion, I suggest that we NOT go down to the level of anatomical terms of motion except where a single motion might also have a complete symbolic meaning, e.g. protrusion of the jaw can be a method of pointing. NB: This still allows use of terms of motion in a definition, e.g. begging might involve dorsiflexion of the hands.

**Comment by DitchingIt** [comment]
No other input received, this suggestion has not been agreed, but it can always be reopened.
