### ISSUE TITLE
NTR: Hiking Behavior

### ISSUE THREAD

**Issue by cmrn-rhi** [obo-behavior/behavior-ontology#109]
I am not very familiar with NBO so this was my best attempt. Apologies and let me know if I can help with improvements!

# Preferred term label

hiking behavior

# Synonyms

hiking, rambling, tramping, bushwalking

## narrower synonyms

hillwalking, fell walking

## broader synonyms

walking *- can be used synonymously with hiking in Ireland and the UK*

# Textual definition

The act of going for a long, vigorous walk, usually on trails or footpaths.

# Definition source

https://en.wikipedia.org/wiki/Hiking

# Suggested parent term

walking behavior (NBO:0000056)
    
_If this term is too narrow, perhaps it's parent term `terrestrial locomotory behavior` (NBO:0000359) would be more appropriate. Did not include any `emotional behavior` or `motivation behavior`; while I could think of examples (e.g. `please behavior`), I couldn't think of universal examples and am unclear on the NBO preference._

# Attribution

https://orcid.org/0000-0002-9578-0788

**Comment by matentzn** [comment]
Thank you @cmrn-rhi Are you confident with Protege? Would you be able to add the term yourself if we give you an id range?

**Comment by cmungall** [comment]
I think the NBO developers need to better define the scope of NBO

clearly hiking is a behavior in the general sense, but I don't think it's
the kind of behavior studied in behavioral neuroscience

I think there is room in OBO for something like a human activity ontology,
corresponding to the activity branch of NCIT

**Comment by matentzn** [comment]
@cmungall I agree this is scope creep; but there is no one really owning NBO anymore. I think the best way to roughly scope nbo is not to say: studied in a lab, but "observable". So while say "walking" is clearly observable, "hiking" is not; you can just see someone walking, and infer from the context (nature, clothes) that this person is hiking. But you cant directly observe hiking. On the other hand, "playing" is clearly important as a behaviour; it would be odd than to say: "playing with food" is allowed, but "playing basketball" is not - both are clearly observable. So I am not sure really whether we should go through the pain of separating human activities (playing basketball, deer hunting for fun, hiking) from behaviors in NBO (hunting behavior, flight behaviour, playing behaviour, smoking behaviour etc). I would rather suggest to model these in a different branch. Unless scope creep comes with a real tangible risk I cant see right now!

**Comment by cmungall** [comment]
I think pragmatically it will be easier to just make term requests of NCIT in this branch:

https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C43431

we are using this branch in ECTO (eg smoking)

if there is no one maintaining NBO right now it makes me even more afraid of it becoming a place where out of scope terms go --> technical debt

**Comment by pmidford** [comment]
I have been watching this thread, and I have to agree.  If we have a 
place for human specific behaviors, it seems a better choice.

**Comment by matentzn** [comment]
Are there any docs on how to make NTRs to NCIT? I assume this is not simply about https://github.com/NCI-Thesaurus/thesaurus-obo-edition/wiki

**Comment by cmrn-rhi** [comment]
> Thank you @cmrn-rhi Are you confident with Protege? Would you be able to add the term yourself if we give you an id range?

Yes I am, but it sounds like that might isn't necessary anymore based on the current discussion.

> we are using this branch in ECTO (eg smoking)

Good to know because the reason I am requesting this term (and others) to support some ECTO new term requests. 

> Are there any docs on how to make NTRs to NCIT?

I can't find any either, but based on `NTR`s that I can see in their issue tracker it doesn't look like there's a template in use. I'll give it a go and see what happens.

**Comment by cmrn-rhi** [comment]
https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues/65

**Comment by DitchingIt** [comment]
The human social activity [issue is now with COB](https://github.com/OBOFoundry/COB/issues/156) and not being pursued by the NBO.
