### ISSUE TITLE
need an NBO base file

### ISSUE THREAD

**Issue by nicolevasilevsky** [obo-behavior/behavior-ontology#117]
could we please create an NBO base file?

This is needed for https://github.com/obophenotype/uberon/issues/2240

**Comment by matentzn** [comment]
The odk base file is already there - the problem is that uberon itself is not in base mode yet..

**Comment by matentzn** [comment]
Cc @anitacaron

**Comment by shawntanzk** [comment]
I now totally get why uberon isnt on base file yet >.< was trying a few things and kept running into error

**Comment by matentzn** [comment]
I will close this ticket here, but @nicolevasilevsky if you are asking this for Mondo, mention it again to me next time we meet and I will sort it out with a small hack, until the general picture problem is solved.

**Comment by nicolevasilevsky** [comment]
This is ultimately needed for Mondo ticket https://github.com/monarch-initiative/mondo/issues/542.
@matentzn, I'll add this to our agenda.

@shawntanzk Thank you so much for all your help! :)
