### ISSUE TITLE
Seizures should be classified as abnormal or pathological process, not phenotype

### ISSUE THREAD

**Issue by dosumis** [obo-behavior/behavior-ontology#119]
The NBO behavioural phenotype branch includes many terms that are defined as abnormal variants of normal processes (defined in the behaviour branch).  Many phenotype ontologies independently define the classes using  standard QE patterns with PATO and NBO behaviour terms.

The branch also includes abnormal/pathological processes - processes that are not variants of normal processes.  Examples include seizures and epilepsy.  These terms would be very useful for defining general, species neutral terms for phenotypes that involve these

**Comment by DitchingIt** [comment]
@dosumis The phenotype branch is being deprecated and @matentzn can better answer what the alternate ontologies will do with this question.

**Comment by DitchingIt** [comment]
@dosumis is withdrawing the draft pull request.
