### ISSUE TITLE
Add migratory behavior

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obo-behavior/behavior-ontology#17]
```
Migration in found in many groups of animals, such as birds, fish, or insects, 
but there is no term for behavior associated with migration in NBO.  I would 
recommend adding this a migratory behavior, rather than migration, which is a 
population level phenomenon that belongs in PCO.

```

Original issue reported on code.google.com by `peter.mi...@gmail.com` on 4 Mar 2013 at 7:40

**Comment by diatomsRcool** [comment]
I would be interested in having terms for diel vertigal migration and seasonal migration

**Comment by diatomsRcool** [comment]
@matentzn

**Comment by matentzn** [comment]
@diatomsRcool I think it would be best if you closed this issue here and replaced it by proper NTRs. I can add the terms, but I need all the exact information what do add because I have no idea of Biology.. :P

**Comment by pmidford** [comment]
+1

**Comment by DitchingIt** [comment]
See #93 and #94
