### ISSUE TITLE
ROBOT  template

### ISSUE THREAD

**Issue by DitchingIt** [obo-behavior/behavior-ontology#190]
At the moment, the proposed process removes links to child classes, unless those children have their own line in the template in which to denote their parents (see PR #189 which was a test using the [template](https://docs.google.com/spreadsheets/d/1hQFy9ffCc1fIbBSt2Hqcsly5t_dSc4Kjgm_VY0D4-lM/edit?usp=sharing) discussed in issue #184). @matentzn I understand you can tweak it?

**Comment by matentzn** [comment]
I added a method for dealing with this, can you look at our PR #189 again and review if you think the child relations now look ok?

**Comment by DitchingIt** [comment]
@matentzn Looks like it does what it should. I hope the process is easy ;-)
