### ISSUE TITLE
Ethology module: Reproductive behavior

### ISSUE THREAD

**Issue by DitchingIt** [obo-behavior/behavior-ontology#192]
Incorporating 11 recast labels, these changes update 26 classes on, and add 16 new ones to, the high level **reproductive behavior NBO:0000010** branch of the NBO's process branch. Each class has only one _is_a_ parent, 30 have a _part_of_ relation, and 19 have at least one listed _participant_. Definitions follow a standard NBO style, fixed sources are given (from which definitions are distilled unless "quoted"), and annotation properties closely follow OBO Foundry recommendations.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu @jannahastings @pmidford @sbello @dosumis and anyone else is welcome to comment here on the changes proposed in the [ROBOT template Google sheet](https://docs.google.com/spreadsheets/d/1fTWjKzoBBGeLuUg9tyVBVNRu_yA0gxblb2bUr-t_HD4/edit?usp=sharing). In addition, I am hoping @matentzn will soon be able to process it as a pull request because I am aware that some contributors prefer to consider and comment there.

**Comment by DitchingIt** [comment]
I have created a graphic to help visualise the new structure proposed for the reproductive behavior branch.
[Reproduction NBO 231124 Graphic.odt](https://github.com/obo-behavior/behavior-ontology/files/13462298/Reproduction.NBO.231124.Graphic.odt)

**Comment by DitchingIt** [comment]
I have modified the label for the new class _NBO:0070014 sexual postural behavior_ within the template (as well as references to it) as I have had the chance to review _NBO:0000355 posture_ for a different (movement) template I am now working on, and prefer _postural behavior_ to my temporary _posturing_ suggestion. (NB: I have not bothered to change the graphic as it retains the correct IDs and was complicated to produce.)

**Comment by aclark-binghamton-edu** [comment]
Comments paused for Thanksgiving...visitors now gone.  Will address Reproductive Behavior module shortly.  Postural behavior sounds better than posturing.

**Comment by DitchingIt** [comment]
Feel free to comment here but bear in mind that conversations are also open at the linked pull request #196

**Comment by DitchingIt** [comment]
My attempts over the last year to change the NBO have not made enough progress to justify pursuing it further. I suggest the commits associated with this issue be removed to reduce confusion in future, since they are dependent on wholesale changes throughout NBO and cannot realistically stand alone.
