### ISSUE TITLE
Add term to generalize tobacco vaping behavior and canabis vaping behavior as vaping behaviors

### ISSUE THREAD

**Issue by matthewhorridge** [obo-behavior/behavior-ontology#195]
This is a new term request.

NBO has two terms related to vaping:  [NBO:0045003](http://purl.obolibrary.org/obo/NBO_0045003) (tobacco vaping behavior) and [NBO:0045006](http://purl.obolibrary.org/obo/NBO_0045006) (canabis vaping behavior).  I'm requesting a common parent that generically describes 'vaping behavior'.

Suggested parent:  [NBO:0001845](http://purl.obolibrary.org/obo/NBO_0001845) (consumption behavior)

Suggested label:  **vaping behavior**

Suggested definition:  **The inhalation and exhalation of aerosolized substance, referred to as vapor, which is produced by an e-cigarette or other device.**

Suggested synonyms:  **vaping**

**Comment by matthewhorridge** [comment]
Thanks for being so receptive to NTRs @DitchingIt!

> Are you comfortable using Protege or another tool yourself to edit NBO? If so, other editors can offer inputs and reviews for pull requests. This is a community ontology, so the more input you can make, the better/ faster the potential output.

I think I could have done this... sorry, I didn't know that this was the best way to go about suggesting changes for this ontology.  I can do this for any future requests :)

**Comment by DitchingIt** [comment]
No problem! If it were an Ethology edit, I would be all over it ;-) But the other spaces in NBO have become a bit 'wild west': I can help out but it's not my ontology - if you can do your own PRs it will be appreciated.
