### ISSUE TITLE
is ataxia a cognitive behavior phenotype?

### ISSUE THREAD

**Issue by cmungall** [obo-behavior/behavior-ontology#21]
```
  is_a NBO:0000266 ! cognitive behavior phenotype
   is_a NBO:0000655 ! sensation behavior phenotype
    is_a NBO:0000656 ! somatic sensation related behavior phenotype
     is_a NBO:0000229 ! vestibular behavior phenotype
      is_a NBO:0000591 ! motor coordination phenotype
       is_a NBO:0000590 ! ataxia *** 
```

@memartone does not believe ataxia to be cognitive

**Comment by memartone** [comment]
This seems to take a very broad view of "cognitive".  IF you look at things like the NIH Toolbox, Cognitive is along side of emotional, sensation and motor.  http://www.nihtoolbox.org/Pages/default.aspx.  That is what I expect most researchers would expect to see.

**Comment by csparr** [comment]
@pmidford Anne said absolutely not.
