### ISSUE TITLE
Determine how to handle weaning behavior

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [obo-behavior/behavior-ontology#31]
May be handled currently as feeding behavior but probably belongs elsewhere.

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt @pmidford @dosumis @csparr 
First, yes, agree that it is not a "feeding behavior".  In the ABO, into which I tried to integrate the NBO term, as I recall, and in which weaning behavior appears, it occurs within/as a child of parental behavior.  

I also provided a definition written by Sue Margulis and I with help from webby resources:  Behavior that restricts access to or reduces demand by offspring for provisioning by parent

Very pointedly, we did NOT want to restrict this to mammals producing milk.  Birds directly feed their young and go through similar interactions with their offspring, behavior that diminishes the reliance on and demands on the parent as source of food.  In other animals, e.g. necrophorus beetle moms, it may occur, but we haven't really been sensitive to the events. GIven that even for NBO users, model organisms are moving way beyond rodents, let's be broad and  prospectively inclusive

**Comment by DitchingIt** [comment]
I'm okay with your definition, but can you give me a better source than my Wikipedia one for it (it doesn't have to be a direct quote)?

**Comment by aclark-binghamton-edu** [comment]
Absolutely, can provide a wealth of slightly different definitions from Barrows 2001 Animal Behavior Desk Reference 2nd ed.  I will take a picture of the set of definitions (they also have refs which I can provide separately) once I have transcribed them.  (Barrow's book is very useful for this.)

**Comment by aclark-binghamton-edu** [comment]
Trivers 1972 Parental Investment and Sexual Selection. pp 136-179 in B. Campbell, Ed, Sexual Selection and the Descent of Man 1871-1971 Aldine Publ, Chicago IL 378 pp

Immelman and Beer are more mammal-forward and insufficiently general.  Also I think it is appropriate to use Trivers' term "resources", not just food or milk, because one thing young animals, esp. vertebrates, may get from parents is protection/warmth/"reassurance"--which if you have ever watched a weaning process, seems to be almost as important as the actual nutrients.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu Do you have a preference between my two options or a third of your own?

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu I'm minded to go with my second option unless there is a reason not to?

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt I would NOT use option two because it seems internally in conflict--ie nuturing is what parents do, not offspring.  A second comment is coming..very, very busy time here at end of semester.

**Comment by aclark-binghamton-edu** [comment]
@DitchingIt OK--first a little discussion. Barrows clearly cited either Trivers paper out of faith--neither offers a useful definition, although I agree that the 3rd phase of parental care is a "weaning period", ie one in which weaning (as a process) takes place.  That is the key problem--weaning is most clearly and generally a process that occurs over a species-typical time and involves an offspring decreasing, even ceasing its use of parental resources.  

Second, , I suggest we use some version of the 2nd definition that Barrows gives and attributes to Klaus Immelmann and Colin Beer's "A Dictionary of Ethology" (1989 Harvard Univ Press, Cambridge MA p 327 in my book, cited by Barrows as 237!) "A mother animal's breaking her offspring's dependence on her, especially with regard to feeding"

BUT, third,  here is Immelmann and Beer's 1989 exact definition: "The breaking of an offspring's dependence on its mother or parents, especially with regard to feeding."  I like this original one better--especially that it references "parents" and we know that many male birds provide offspring food and I speak from experience that they have some creative ways to get offspring to stop demanding food or feeding. 

SO--finally---IF I were going to construct a definition starting with "behavior", I would say "Behavior that promotes the breaking of an offspring's dependence on parental resources, especially food resources (Immelmann and Beer 1989)".  In every definition we have found, it is understood that it is parental behavior that enforces the process, and logically it goes under parental behavior, not nurturing behavior.  (Ask anyone being weaned!)

Whew--what do you think?
