### ISSUE TITLE
Standardise relationship of NBO to GO.

### ISSUE THREAD

**Issue by dosumis** [obo-behavior/behavior-ontology#34]
NBO includes:
- NBO terms with xrefs to GO ids
- GO terms used compositionally to define NBO terms via some class restriction (relationship).

These need to be harmonised, or if justified, documented.

**Comment by reality** [comment]
It seems that if a GO term is relatively equivalent to an NBO term, then xref would be used, while if a combination/composition of GO terms is necessary to define a novel term for NBO, the latter is used?

**Comment by matentzn** [comment]
Closed in favour of https://github.com/obo-behavior/behavior-ontology/issues/101
