### ISSUE TITLE
Decide how to support commonly used assays 

### ISSUE THREAD

**Issue by csparr** [obo-behavior/behavior-ontology#35]
- [ ] Find the Assay Ontology that is in progress
- [ ] Ensure that they are well-supported by this ontology

**Comment by dosumis** [comment]
Consider using [ECO](https://github.com/evidenceontology/evidenceontology)

**Comment by leechuck** [comment]
I'll close this issue; assays are not in the scope of NBO and should be handled by ECO or OBI, and combined with phenotypes in the datamodel.
