### ISSUE TITLE
NTR: grazing behavior

### ISSUE THREAD

**Issue by pbuttigieg** [obo-behavior/behavior-ontology#44]
Greetings NBO! 

At ENVO, @TaskeHAMANO and I are working on adding some classes such as `pasturable land` that would benefit from the addition of "grazing behaviour".

I would imagine this is useful for ontologies like ECOCORE too.

Suggested definition: 
"A feeding behavior during which an animal ingests biomass produced by a plant or other primary producer"
dbxref: https://en.wikipedia.org/wiki/Grazing

We can define "primary producer" in ECOCORE

This will crosslink with AgrO's treatment of the agricultural practices associated with this behaviour: https://github.com/AgriculturalSemantics/agro/issues/32

Thoughts?

**Comment by leechuck** [comment]
Could you add and send me diff/pull request for this, please? I will
commit.

**Comment by pbuttigieg** [comment]
>Could you add and send me diff/pull request for this, please? I will
commit. 

@TeskeHAMANO is working on that now. 

In the meantime, the axioms on [feeding behavior](http://purl.obolibrary.org/obo/NBO_0000079) feel a bit funny (CC @gkoutos @dosumis) 

![image](https://user-images.githubusercontent.com/2276146/30421878-157391b4-9936-11e7-9a97-56f6fb68b204.png)

That's `food` as a `chemical role` from CHEBI and an :warning: obsolete :warning: PATO class for liquid (is the label import  broken?).

Isn't feeding always to do with food? Is there no class for drinking behaviour to account for liquids? There is one for [`drinking behavior phenotype`](http://purl.obolibrary.org/obo/NBO_0000540)

The range of `has participant` allows roles and qualities as participants, however, perhaps it would be better to revise that to: 

```
'consumption behavior'
  and has_participant some 
  (
    (
      ['solid environmental material'](http://purl.obolibrary.org/obo/ENVO_01000814)
    or 
      ['liquid enviromental material'](http://purl.obolibrary.org/obo/ENVO_01000815
    ) and 'has role' some 'food' 
  )

``` 

@Public-Health-Bioinformatics it would be even better if FOODON created defined classes (to be filled by inference alone) for "solid food" and "liquid food", in a similar way to how ENVO handles materials. Then NBO can  import those rather than the ENVO classes above. xref https://github.com/FoodOntology/foodon/issues/35

**Comment by TaskeHAMANO** [comment]
I have submitted a PR.
Some explanation are below.

* We used 0050000 as NBO ID. (It looks no one uses this range, referencing nbo-idranges.owl)
* "has_alternative_id" property has not been annotated yet
* We used ORCID as created_by property value in order to track person's background easily

**Comment by Public-Health-Bioinformatics** [comment]
Foodon now has these terms, referencing PATO qualities:

solid food product: 'food material' and ('has quality' some 'quality of a solid')
liquid food product: 'food material' and ('has quality' some 'quality of a liquid')

and 
'food material' : 'material entity' and ('has role' some food)
