### ISSUE TITLE
latest nbo in obo format

### ISSUE THREAD

**Issue by RLWOHIO** [obo-behavior/behavior-ontology#52]
Could you make the latest nbo ontology also available in obo format?  I am unable to convert nbo.owl to nbo.obo by either robot or Protege.  Thanks!

**Comment by cmungall** [comment]
Hmm, if the nbo release managers are using the Makefile this should be done automatically:

https://github.com/obo-behavior/behavior-ontology/blob/8338bc2f14b3985629e4ac30b8aa623857cce82a/src/ontology/Makefile#L66-L71

@reality @pmidford ping me if you want help

**Comment by reality** [comment]
Seems like there are some untranslateable axioms which mean that robot can't create the obo version; there are many but for e.g.:

ERROR MASKING ERROR «the axiom is not translated : SubClassOf(<http://purl.obolibrary.org/obo/NBO_0000754> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000056> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/GO_0042747> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/uberon#has_quality> <http://purl.obolibrary.org/obo/PATO_0000001>))))»
java.lang.Exception

 Any ideas @cmungall ?

**Comment by reality** [comment]
Seems like there are some untranslateable axioms which mean that robot can't create the obo version; there are many but for e.g.:

ERROR MASKING ERROR «the axiom is not translated : SubClassOf(<http://purl.obolibrary.org/obo/NBO_0000754> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000056> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/GO_0042747> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/uberon#has_quality> <http://purl.obolibrary.org/obo/PATO_0000001>))))»
java.lang.Exception

I'll look into it. Any ideas @cmungall ?

**Comment by cmungall** [comment]
it's not a big deal, the .obo is not expected to be as expressive. The untranslatable axioms go in a header line that is ignored by most .obo parsers - but it's often preferable to get rid of that line with a hacky `grep -v ^owl-axioms`.

Having said that, this is a super-odd axiom. It looks like it was derived by [relaxing](http://robot.obolibrary.org/relax) the equiv axiom in NBO: `'REM sleep' EquivalentTo BFO_0000056 some (GO_0042747 and (has_quality some PATO_0000001))`

 * http://purl.obolibrary.org/obo/BFO_0000056 does not exist
 * in general, equivalence axioms should have a genus (named class) in the intersection
 * `FOO and has_quality "quality"` is equivalent to `FOO`
 * looks like this is a roundabout way of making an equivalence axiom? The broader issue here is overlap with GO

**Comment by cmungall** [comment]
It looks like you have committed an empty file:

https://github.com/obo-behavior/behavior-ontology/blob/master/nbo.obo

I suggest removing this until you have figured out the obo export. Let me know if you have problems.

Once you have figured out the obo export, we can add a PURL for it on the obo side

**Comment by reality** [comment]
Fixed in current release
