### ISSUE TITLE
Definition of alcohol aversion (NBO_0000139) should be revised

### ISSUE THREAD

**Issue by matentzn** [obo-behavior/behavior-ontology#53]
Liquid aversion is, in my opinion, falsely asserted to be a **subclass** of alcohol aversion. (Liquid preference and regulation of alcohol preference are correctly classified). It should be the other way around.

I would also like to point out the slightly idiosyncratic definitions of these two classes: Why does the definition of liquid aversion (and preference!) contain a restriction on the decreased rate quality (towards some liquid consumption), while the respective definitions involving alcohol do not? Lastly, and least important, the human-readable definition of "regulation of alcohol preference behavior" contains a typo (alchohol instead of alcohol).

**Comment by reality** [comment]
also: to add under substance aversion, since that is more suitable than subclass of liquid aversion too
