### ISSUE TITLE
We need an NBO base product (without imports)

### ISSUE THREAD

**Issue by matentzn** [obo-behavior/behavior-ontology#59]
NBO pulls in a lot of old versions of ontologies that are causing trouble for importing ontologies. Along with many other OBO ontologies, we are adding base products of ontologies everywhere that contain only the axioms that are *owned* by the ontology, and omitting any imports of axioms that are owned by another ontology (such as axioms from GO or UBERON). I could do this, perhaps even move NBO to the new ODK release pipeline, I just need write access to NBO. @cmungall @dosumis

**Comment by dosumis** [comment]
Agree - NBO should definitely be on ODK - ASAP

**Comment by cmungall** [comment]
+1

>
