### ISSUE TITLE
NTR: predator avoidance behavior

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#60]
For new term requests, please provide the following information:

## Preferred term label

predator avoidance behavior

## Textual definition

an avoidance behavior engaged in by prey that reduces the success of a predator without the prey actually attacking the predator

## Suggested parent term

avoidance behavior http://purl.obolibrary.org/obo/NBO_0000635

## Attribution

http://orcid.org/0000-0002-2908-3327

Term is needed for ecocore https://github.com/EcologicalSemantics/ecocore/issues/2

**Comment by matentzn** [comment]
https://github.com/obo-behavior/behavior-ontology/pull/80/files
