### ISSUE TITLE
NTR: trapping behavior

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#61]
For new term requests, please provide the following information:

## Preferred term label
trapping behavior

## Textual definition
a predator behavior involving subduing prey using a structure or modification of the environment created by the predator for that purpose

## Suggested parent term
predator behavior http://purl.obolibrary.org/obo/NBO_0000089

Attribution
http://orcid.org/0000-0002-2908-3327

Term is needed for ecocore EcologicalSemantics/ecocore#2

**Comment by matentzn** [comment]
https://github.com/obo-behavior/behavior-ontology/pull/80/files
