### ISSUE TITLE
NTR: ambush behavior

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#62]
For new term requests, please provide the following information:

## Preferred term label
ambush behavior

## Textual definition
a predator behavior involving a surprise attack on unsuspecting prey. The predator remains in one place and waits for prey to come near. The predator conceals itself and then subdues its prey with its own body or body parts.

## Suggested parent term
predator behavior http://purl.obolibrary.org/obo/NBO_0000089

Attribution
http://orcid.org/0000-0002-2908-3327

Term is needed for ecocore EcologicalSemantics/ecocore#2

**Comment by diatomsRcool** [comment]
Any thoughts?

**Comment by matentzn** [comment]
https://github.com/obo-behavior/behavior-ontology/pull/80/files
