### ISSUE TITLE
NTR: hunting behavior

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#63]
For new term requests, please provide the following information:

## Preferred term label
hunting behavior

## Textual definition
a predator behavior involving actively stalking prey over a distance

## Suggested parent term
predator behavior http://purl.obolibrary.org/obo/NBO_0000089

Attribution
http://orcid.org/0000-0002-2908-3327

Term is needed for ecocore EcologicalSemantics/ecocore#2

**Comment by diatomsRcool** [comment]
Any thoughts?

**Comment by matentzn** [comment]
Closed https://github.com/obo-behavior/behavior-ontology/pull/74
