### ISSUE TITLE
NBO should not hard code axioms that belong to another ontology

### ISSUE THREAD

**Issue by matentzn** [obo-behavior/behavior-ontology#69]
Currently, there are plenty of CHEBI, GO, PATO and UBERON axioms hard-wired into NBO. These should be all pulled in through the import modules.

**Comment by matentzn** [comment]
@leechuck @reality @dosumis 

FYI - I will strip them out next Monday after I merge the current PRs.

**Comment by DitchingIt** [comment]
Is this issue closed?

**Comment by DitchingIt** [comment]
Dealth with by #71
