### ISSUE TITLE
need definition for bonding behavior

### ISSUE THREAD

**Issue by nicolevasilevsky** [obo-behavior/behavior-ontology#75]
NBO_0000043  bonding behavior
**proposed def:** A behavior that occurs between two individuals, such as parent and child, and involves an emotional attachment that implies a special and focused relationship.
**source:** PMID:29327315

**Comment by matentzn** [comment]
Nicole, do you want to just do a PR? That will have the quickest turnaround. Just be careful with picking the next available ID..

**Comment by nicolevasilevsky** [comment]
This term already exists, it just needs a def. I tried to edit this in Protege but was getting crazy diffs when I edited. I will do a PR and you can see.

**Comment by nicolevasilevsky** [comment]
I can't do a PR, I get this error:
remote: Permission to obo-behavior/behavior-ontology.git denied to nicolevasilevsky.
fatal: unable to access 'https://github.com/obo-behavior/behavior-ontology.git/': The requested URL returned error: 403
