### ISSUE TITLE
Move NBO edit to functional syntax to allow easier diffing

### ISSUE THREAD

**Issue by matentzn** [obo-behavior/behavior-ontology#78]

**Comment by DitchingIt** [comment]
@matentzn Any update on this?

**Comment by matentzn** [comment]
Great ticket for you! Just use protege s save as function. Make pull request and ask for me as a reviewer!

**Comment by DitchingIt** [comment]
@matentzn Just because I'm working on the weekend doesn't mean you need to! I don't have anything else to do... Anyway, **NEXT WEEK** you might tell me what 
> Just use protege s save as function

means, if I haven't figured it out before hand.

**Comment by DitchingIt** [comment]
Done #130
