### ISSUE TITLE
add xref for  NBO:0000415 ! corneal reflex

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obo-behavior/behavior-ontology#8]
```
GO:0060082 ! eye blink reflex

or demote:

synonym: "blink reflex" EXACT []
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 14 Dec 2011 at 8:35

**Comment by matentzn** [comment]
@DitchingIt this is super easy to fix, you should just do it as part of #136
