### ISSUE TITLE
NTR: alcohol consumption

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#84]
behavior related to the intake of alcohol

subclass of "consumption of an addictive substance"

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
alcohol consumption
id:
name: alcohol consumption
def: "Behavior related to the intake of alcohol." []
is_a: NBO:0001884 ! consumption of an addictive substance
property_value: created_by "Nicolas Matentzoglu" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor http://orcid.org/0000-0002-2908-3327 xsd:string
property_value: http://purl.org/dc/elements/1.1/date 2019-09-03T13:51:02Z xsd:string

**Comment by matentzn** [comment]
In personal conversation, we decided to model this in a post-composed fashion until more community requests come in: `'consumption of an addicitive substance' and 'has input' some alcohol)
