### ISSUE TITLE
NTR: chewing

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#86]
nicotine consumption behavior that involves holding specially-prepared tobacco leaves in the mouth for absorption of nicotine through oral tissues

subclass of "nicotine consumption"

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
chewing
id: 
name: chewing
def: "Nicotine consumption behavior that involves holding specially-prepared tobacco leaves in the mouth for absorption of nicotine through oral tissues." []
is_a: NBO:0002086 ! nicotine consumption behavior
property_value: created_by "Nicolas Matentzoglu" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor http://orcid.org/0000-0002-2908-3327 xsd:string
property_value: http://purl.org/dc/elements/1.1/date 2019-09-03T13:51:02Z xsd:string

**Comment by matentzn** [comment]
Use http://purl.obolibrary.org/obo/NBO_0000073 and post-compose as discussed in personal discussion.
