### ISSUE TITLE
NTR: snuffing

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#87]
nicotine consumption behavior that involves inhaling finely ground tobacco leaves via the nose

subclass of "nicotine consumption"

http://orcid.org/0000-0002-2908-3327

**Comment by diatomsRcool** [comment]
snuffing
id: 
name: snuffing
def: "Nicotine consumption behavior that involves inhaling finely ground tobacco leaves via the nose." []
is_a: NBO:0002086 ! nicotine consumption behavior
property_value: created_by "Nicolas Matentzoglu" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor http://orcid.org/0000-0002-2908-3327 xsd:string
property_value: http://purl.org/dc/elements/1.1/date 2019-09-03T13:51:02Z xsd:string

**Comment by matentzn** [comment]
Fixed.
