### ISSUE TITLE
NTR: place for work behavior terms

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#88]
I need terms for:
house work: behaviors associated with maintaining and cleaning a home
yard work: behaviors associated with maintaining and cleaning a yard
care giving: behaviors associated with providing care for another person
Any suggestions on where these should go?

**Comment by matentzn** [comment]
I dont think you will get answers here; give it your best shot for the terms and I will add them again! (like the other ones).

**Comment by diatomsRcool** [comment]
I just pushed to a branch called "work". Let me know what you think.

**Comment by DitchingIt** [comment]
This issue is more [usefully discussed under COB](https://github.com/OBOFoundry/COB/issues/156).
