### ISSUE TITLE
NTR: place for recreation activities

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#89]
I need the following terms:
dance
team sports
conditioning
TV watching
reading
I'm not sure where they should go. Under "locomotor play"? Maybe not TV watching and reading.

**Comment by matentzn** [comment]
I dont think you will get answers here; give it your best shot for the terms and I will add them again! (like the other ones).

**Comment by DitchingIt** [comment]
This issue is more [usefully discussed under COB](https://github.com/OBOFoundry/COB/issues/156).

**Comment by matentzn** [comment]
This requires no matter what a concerted effort at a lifestyle ontology separate from NBO

**Comment by diatomsRcool** [comment]
agree
