### ISSUE TITLE
NTR: caffeine consumption

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#90]
behavior related to the intake of caffeine

subclass of "consumption of an addictive substance"

http://orcid.org/0000-0002-2908-3327

**Comment by matentzn** [comment]
I think this may be out of scope for NBO.. drinking ok, but drinking of specific substances will be bloat the ontology a lot; What do you think @dosumis

**Comment by echesler** [comment]
Hi, I'm wearing my NIDA Center for Systems Neurogenetics of Addiction hat today. We do need to evaluate drinking or consumption of specific substances, vs. general "consumption of an addictive substance"

**Comment by diatomsRcool** [comment]
caffeine consumption
id: 
name: caffeine consumption
def: "Behavior related to the intake of caffeine" []
is_a: NBO:0001884 ! consumption of an addictive substance
property_value: created_by "Nicolas Matentzoglu" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor http://orcid.org/0000-0002-2908-3327 xsd:string
property_value: http://purl.org/dc/elements/1.1/date 2019-09-03T13:51:02Z xsd:string

**Comment by matentzn** [comment]
@echesler Are you annotating against NBO directly? You could solve the issue at annotation time by combining the terms "consumption of an addictive substance" with the term for "caffeine"!

**Comment by dosumis** [comment]
I'm inclined to allow it for addictive substances long as we have  a pattern for linking to ChEBI.  Post composition always sounds good in theory, but really needs to be  carefully controlled to be useable for clear semantic intepretation.

**Comment by matentzn** [comment]
Ok! So @echesler and @diatomsRcool 

If you need to use an NBO term directly, please reopen this request and I will add a special term for "caffeine consumption". If you need the term to post-compose your own ontology terms (like in @diatomsRcool case), lets stick with the more general "consumption of" or "drinking" terms and combine it with a suitable "caffeine" term to avoid combinatorial explosion. Please don't hesitate to contact me about any special terms you need, but be mindful that we should try to avoid severe degrees of combinatorial explosions, like adding a term for every possible substance that can theoretically be consumed. No objections to important ones though!
