### ISSUE TITLE
NTR: diel vertical migration

### ISSUE THREAD

**Issue by diatomsRcool** [obo-behavior/behavior-ontology#93]
For new term requests, please provide the following information:

## Preferred term label

diel vertical migration

## Textual definition

a circadian behavior of an organism that involves regular movement up and down in the water column in 24 hour cycles. I'm not sure if the "migratory" nature is important here. Is it important to capture that many individuals are moving together?

## Suggested parent term

Circadian behavior

## Attribution

http://orcid.org/0000-0002-2908-3327

**Comment by DitchingIt** [comment]
@diatomsRcool @dosumis @aclark-binghamton-edu @pmidford 
Dingle suggests on page 4 that this is a form of 'commuting' within _Station keeping_ and not _Migration_ (Dingle H. Migration: the biology of life on the move. Oxford University Press, USA; 2014.) However Bandara notes that a seasonal variety of vertical migration also exists; I prefer to keep the vertical components together and anyway, the term migration has been widely used in the vertical sense for many years. Following #169, I propose to add this term with the following modifications:
## Parent
migration
## Source
Bandara K, Varpe Ø, Wijewardene L, Tverberg V, Eiane K. Two hundred years of zooplankton vertical migration research. Biological Reviews. 2021 Aug;96(4):1547-89.

**Comment by aclark-binghamton-edu** [comment]
This and the previous issues on rhythmic behavior and migration revolve around what one considers "primary".  Is the repetitiveness primary, scales secondary?  Are the scales of movement primary?  Is the distance primary--and what is long enough to be migration?  Even "resident birds" move their ranges between breeding, fall foraging and winter foraging.  
       Several possible solutions that still offer all the terms.  But again, the "top parent" term will represent a decision between the above choices about what is the more important umbrella or organizer.

**Comment by DitchingIt** [comment]
@aclark-binghamton-edu I agree, but I think we need to offer users our best attempt at a compromise which we can move forward with. I'm only saying what I prefer, but I'd be perfectly willing to go with it if you felt strongly that scales were primary; I just want to move forward. Do you have a preferred "top parent" term?
