### ISSUE TITLE
NTR: tobacco consumption and cannabis consumption

### ISSUE THREAD

**Issue by LCCarmody** [obo-behavior/behavior-ontology#98]
This is a request to either add or rework the 'smoking behavior' branch

NTR:

-consumption behavior
--tobacco consumption 
---tobacco chewing behavior (or chewing tobacco behavior?)
---tobacco vaping behavior
---tobacco smoking behavior
----tobacco cigar smoking behavior 
----tobacco cigarette smoking behavior
----tobacco pipe smoking behavior

--cannabis consumption
---cannabis smoking behavior
---cannabis vaping behavior
---cannabis oil consumption

I know there are other methods of to consume these, but I don't think we need the fine detail. I would be okay if the cigar/cigarette/pipe smoking behavior were obsoleted, but since the terms are already there, I kept them in the hierarchy.

**Comment by matentzn** [comment]
@LCCarmody Yes, this is correct IMO. Would you be so amazing and actually just do this PR yourself? I will add you as an editor if you agree; you just need to make a pull request as usual and create this hierarchy in protege. If new terms are required, you do them, as usual, in your ID space.. :P

**Comment by matentzn** [comment]
Awwwwesommme! There you go:
https://github.com/obo-behavior/behavior-ontology/blob/df41b0ce8bf68afb19ab630a8b0a4a7f4a804d3e/src/ontology/nbo-idranges.owl#L51

**Comment by matentzn** [comment]
(send you an invite as well. Remember to do Pull requests, else everything same as MAXO (Make sure the ids are NBO ids)!

**Comment by LCCarmody** [comment]
Sure!
